 server:
   port: 8888

 spring:
   application:
     name: config-service
   cloud:
     config:
       server:
         git:
           uri: https://github.com/praneetn/config-repo
           default-label: master
           timeout: 10
           clone-on-start: true
           force-pull: true

